import { getSession } from "../auth/session.js";
import { createAdminGraphqlClient } from "../shopify/admin-graphql.js";
import type { MigrationPlan } from "./types.js";
type Report = { module: string; status: "completed" | "skipped" | "failed"; count?: number; message?: string };
const pagesQuery = `query Pages { pages(first: 250) { nodes { title handle body isPublished templateSuffix } } }`;
const definitionsQuery = `query Definitions { metafieldDefinitions(first: 250, ownerType: PRODUCT) { nodes { name namespace key type description pinned } } }`;
const createPage = `mutation Page($page: PageCreateInput!) { pageCreate(page: $page) { page { id handle } userErrors { field message } } }`;
const createDefinition = `mutation Definition($definition: MetafieldDefinitionInput!) { metafieldDefinitionCreate(definition: $definition) { createdDefinition { id namespace key } userErrors { field message } } }`;
const createTheme = `mutation Theme($name: String!, $source: URL!) { themeCreate(name: $name, source: $source) { theme { id name role } userErrors { field message } } }`;
const menusQuery = `query Menus { menus(first: 50) { nodes { title handle items { title url type items { title url type } } } } }`;
const createMenu = `mutation Menu($title: String!, $handle: String!, $items: [MenuItemCreateInput!]!) { menuCreate(title: $title, handle: $handle, items: $items) { menu { id handle } userErrors { field message } } }`;
const filesQuery = `query Files { files(first: 100, query: "status:ready") { nodes { alt contentType url } } }`;
const createFiles = `mutation Files($files: [FileCreateInput!]!) { fileCreate(files: $files) { files { id url } userErrors { field message } } }`;
function requiredSession(shop: string) {
  const session = getSession(shop);
  if (session) return session;
  const sourceStore = process.env.SOURCE_STORE || "dearbody-colombia-f1vuyjy7.myshopify.com";
  const destinationStore = process.env.DESTINATION_STORE || "dearbody-template-client-hjsvcqyt.myshopify.com";
  if (shop === sourceStore && process.env.SOURCE_ACCESS_TOKEN) return { shop, accessToken: process.env.SOURCE_ACCESS_TOKEN, scopes: [], installedAt: "server-configured" };
  if (shop === destinationStore && process.env.DESTINATION_ACCESS_TOKEN) return { shop, accessToken: process.env.DESTINATION_ACCESS_TOKEN, scopes: [], installedAt: "server-configured" };
  throw new Error(`La tienda ${shop} aún no está autorizada en la app.`);
}
export async function executeMigration(plan: MigrationPlan): Promise<{ reports: Report[] }> {
  if (plan.selection.products || plan.selection.metafields) throw new Error("Productos y valores de metacampos están bloqueados en esta plantilla.");
  const source = requiredSession(plan.sourceShop); const destination = requiredSession(plan.destinationShop);
  const from = createAdminGraphqlClient(source.shop, source.accessToken); const to = createAdminGraphqlClient(destination.shop, destination.accessToken); const reports: Report[] = [];
  if (plan.selection.pages) { const result = await from.query<{ pages: { nodes: Array<{ title: string; handle: string; body: string; isPublished: boolean; templateSuffix: string | null }> } }>(pagesQuery); let count = 0; for (const page of result.pages.nodes) { if (!plan.dryRun) { const created = await to.query<{ pageCreate: { userErrors: Array<{ message: string }> } }>(createPage, { page: { title: page.title, handle: page.handle, body: page.body, isPublished: page.isPublished, templateSuffix: page.templateSuffix } }); if (created.pageCreate.userErrors.length) throw new Error(created.pageCreate.userErrors.map((e) => e.message).join("; ")); } count++; } reports.push({ module: "pages", status: plan.dryRun ? "skipped" : "completed", count, message: plan.dryRun ? "Simulación; no se escribieron páginas." : undefined }); }
  if (plan.selection.metafieldDefinitions) { const result = await from.query<{ metafieldDefinitions: { nodes: Array<{ name: string; namespace: string; key: string; type: string; description: string | null; pinned: boolean }> } }>(definitionsQuery); let count = 0; for (const definition of result.metafieldDefinitions.nodes) { if (!plan.dryRun) { const created = await to.query<{ metafieldDefinitionCreate: { userErrors: Array<{ message: string }> } }>(createDefinition, { definition: { name: definition.name, namespace: definition.namespace, key: definition.key, type: definition.type, description: definition.description, ownerType: "PRODUCT", pin: definition.pinned } }); const errors = created.metafieldDefinitionCreate.userErrors; if (errors.length && !errors.some((e) => /already exists|taken/i.test(e.message))) throw new Error(errors.map((e) => e.message).join("; ")); } count++; } reports.push({ module: "metafieldDefinitions", status: plan.dryRun ? "skipped" : "completed", count, message: plan.dryRun ? "Simulación; no se escribieron definiciones." : undefined }); }
  if (plan.selection.theme) { if (plan.dryRun) reports.push({ module: "theme", status: "skipped", message: "Simulación; el tema no se publicó." }); else { const source = `${process.env.SHOPIFY_APP_URL || ""}/template-theme.zip`; const created = await to.query<{ themeCreate: { theme: { id: string } | null; userErrors: Array<{ message: string }> } }>(createTheme, { name: "Dearbody Template", source }); if (created.themeCreate.userErrors.length || !created.themeCreate.theme) throw new Error(created.themeCreate.userErrors.map((e) => e.message).join("; ") || "Shopify no creó el tema"); reports.push({ module: "theme", status: "completed", count: 1 }); } }
  if (plan.selection.menus) { const result = await from.query<{ menus: { nodes: Array<{ title: string; handle: string; items: Array<{ title: string; url: string; type: string; items: Array<{ title: string; url: string; type: string }> }> }> } }>(menusQuery); let count = 0; for (const menu of result.menus.nodes) { if (!plan.dryRun) { const created = await to.query<{ menuCreate: { userErrors: Array<{ message: string }> } }>(createMenu, { title: menu.title, handle: menu.handle, items: menu.items.map((item) => ({ title: item.title, url: item.url, type: item.type, items: item.items.map((child) => ({ title: child.title, url: child.url, type: child.type })) })) }); if (created.menuCreate.userErrors.length && !created.menuCreate.userErrors.some((e) => /already exists|taken/i.test(e.message))) throw new Error(created.menuCreate.userErrors.map((e) => e.message).join("; ")); } count++; } reports.push({ module: "menus", status: plan.dryRun ? "skipped" : "completed", count }); }
  if (plan.selection.files) { const result = await from.query<{ files: { nodes: Array<{ alt: string | null; contentType: string | null; url: string }> } }>(filesQuery); if (plan.dryRun) reports.push({ module: "files", status: "skipped", count: result.files.nodes.length }); else { const created = await to.query<{ fileCreate: { files: Array<{ id: string }>; userErrors: Array<{ message: string }> } }>(createFiles, { files: result.files.nodes.map((file) => ({ originalSource: file.url, alt: file.alt, contentType: file.contentType })) }); if (created.fileCreate.userErrors.length) throw new Error(created.fileCreate.userErrors.map((e) => e.message).join("; ")); reports.push({ module: "files", status: "completed", count: created.fileCreate.files.length }); } }
  if (plan.selection.collections) reports.push({ module: "collections", status: "failed", message: "Las colecciones se mantienen como módulo opcional y requieren mapeo de reglas." });
  return { reports };
}
