import { getSession } from "../auth/session.js";
import { createAdminGraphqlClient } from "../shopify/admin-graphql.js";
import type { MigrationPlan } from "./types.js";
type Report = { module: string; status: "completed" | "skipped" | "failed"; count?: number; message?: string };
const pagesQuery = `query Pages { pages(first: 250) { nodes { title handle body isPublished templateSuffix } } }`;
const definitionsQuery = `query Definitions { metafieldDefinitions(first: 250, ownerType: PRODUCT) { nodes { name namespace key type description pinned } } }`;
const createPage = `mutation Page($page: PageCreateInput!) { pageCreate(page: $page) { page { id handle } userErrors { field message } } }`;
const createDefinition = `mutation Definition($definition: MetafieldDefinitionInput!) { metafieldDefinitionCreate(definition: $definition) { createdDefinition { id namespace key } userErrors { field message } } }`;
function requiredSession(shop: string) { const session = getSession(shop); if (!session) throw new Error(`La tienda ${shop} aún no está autorizada en la app.`); return session; }
export async function executeMigration(plan: MigrationPlan): Promise<{ reports: Report[] }> {
  if (plan.selection.products || plan.selection.metafields) throw new Error("Productos y valores de metacampos están bloqueados en esta plantilla.");
  const source = requiredSession(plan.sourceShop); const destination = requiredSession(plan.destinationShop);
  const from = createAdminGraphqlClient(source.shop, source.accessToken); const to = createAdminGraphqlClient(destination.shop, destination.accessToken); const reports: Report[] = [];
  if (plan.selection.pages) { const result = await from.query<{ pages: { nodes: Array<{ title: string; handle: string; body: string; isPublished: boolean; templateSuffix: string | null }> } }>(pagesQuery); let count = 0; for (const page of result.pages.nodes) { if (!plan.dryRun) { const created = await to.query<{ pageCreate: { userErrors: Array<{ message: string }> } }>(createPage, { page: { title: page.title, handle: page.handle, body: page.body, isPublished: page.isPublished, templateSuffix: page.templateSuffix } }); if (created.pageCreate.userErrors.length) throw new Error(created.pageCreate.userErrors.map((e) => e.message).join("; ")); } count++; } reports.push({ module: "pages", status: plan.dryRun ? "skipped" : "completed", count, message: plan.dryRun ? "Simulación; no se escribieron páginas." : undefined }); }
  if (plan.selection.metafieldDefinitions) { const result = await from.query<{ metafieldDefinitions: { nodes: Array<{ name: string; namespace: string; key: string; type: string; description: string | null; pinned: boolean }> } }>(definitionsQuery); let count = 0; for (const definition of result.metafieldDefinitions.nodes) { if (!plan.dryRun) { const created = await to.query<{ metafieldDefinitionCreate: { userErrors: Array<{ message: string }> } }>(createDefinition, { definition: { name: definition.name, namespace: definition.namespace, key: definition.key, type: definition.type, description: definition.description, ownerType: "PRODUCT", pin: definition.pinned } }); const errors = created.metafieldDefinitionCreate.userErrors; if (errors.length && !errors.some((e) => /already exists|taken/i.test(e.message))) throw new Error(errors.map((e) => e.message).join("; ")); } count++; } reports.push({ module: "metafieldDefinitions", status: plan.dryRun ? "skipped" : "completed", count, message: plan.dryRun ? "Simulación; no se escribieron definiciones." : undefined }); }
  for (const module of ["theme", "menus", "files", "collections"] as const) if (plan.selection[module]) reports.push({ module, status: "failed", message: "Este módulo requiere un adaptador de transferencia específico y no se ejecutó parcialmente." });
  return { reports };
}
